/**
 * @author boratanrikulu
 * If you have any question about the project, you can contact me at http://boratanrikulu.me/contact
 */
package flighttickets.CustomerPages;

import flighttickets.DataBaseProcesses.DataBaseConnecter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

public class ChooseSeat extends javax.swing.JFrame {

	private Connection connection;
	private int planeId;
	private int customerId;
	private int seatNumber;
	private BuyTicket buyTicket;
	
	public ChooseSeat(int planeId, int customerId, BuyTicket buyTicket) {
		initComponents();
		
		DataBaseConnecter connecter = new DataBaseConnecter(); // makes a connection to the database
		
		this.connection = connecter.getConnection();
		this.planeId = planeId;
		this.customerId = customerId;
		this.buyTicket = buyTicket;
		setRadioActionCommands(); // sets ActionCommands for the all radio buttons to use them later
		setUnvisibleTakenSeats(); // makes invisible the seats that is already taken
		setPrices(); // takes prices from the database
	}
	
	public void setPrices() {
		String query = "select * from flights where id = ?";
		
		try {
			PreparedStatement preparedStatement = connection.prepareStatement(query);
			
                        preparedStatement.setInt(1, this.planeId);
			
                        ResultSet resultSet = preparedStatement.executeQuery();
			if(resultSet.next()) { // set prices for all types
				this.firstClassPrice.setText("$" + String.valueOf(resultSet.getInt("firstClassPrice")));
				this.premiumClassPrice.setText("$" + String.valueOf(resultSet.getInt("premiumClassPrice")));
				this.mainCabinPrice.setText("$" + String.valueOf(resultSet.getInt("mainCabinPrice")));
			}
		} catch (SQLException ex) {
			Logger.getLogger(PaymentPage.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	public void setRadioActionCommands() {
		int counter = 0; // sets names of radios to use later.
		
		for (Enumeration<AbstractButton> buttons = seatsButtonGroup.getElements(); buttons.hasMoreElements();) {
			counter++;
			AbstractButton button = buttons.nextElement();
			button.setActionCommand(Integer.toString(counter));
		}
	}
	
	public void setUnvisibleTakenSeats() {
		for (Enumeration<AbstractButton> buttons = seatsButtonGroup.getElements(); buttons.hasMoreElements();) {
			AbstractButton button = buttons.nextElement();
			
			if(checkSeatStatus(Integer.valueOf(button.getActionCommand()))) {
				button.setVisible(false); // makes the seat invisible if it is already taken
			}
		}
	}
	
	public boolean checkSeatStatus(int seatNumber) {
		String query = "select * from sold_tickets where planeId = ? and seatNumber = ?";
		
		try {
			PreparedStatement preparedStatement = connection.prepareStatement(query);
			
			preparedStatement.setInt(1, this.planeId);
			preparedStatement.setInt(2, seatNumber);
			
			ResultSet resultSet = preparedStatement.executeQuery();
			if(resultSet.next()) {
				return true; // returns true if there is a matching seat number.
			}
			return false;
		} catch (SQLException ex) {
			Logger.getLogger(ChooseSeat.class.getName()).log(Level.SEVERE, null, ex);
			return false;
		}
	}
		
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	 @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                seatsButtonGroup = new javax.swing.ButtonGroup();
                jPanel1 = new javax.swing.JPanel();
                buyTheTicketButton = new javax.swing.JButton();
                firstClassRadio1 = new javax.swing.JRadioButton();
                firstClassRadio2 = new javax.swing.JRadioButton();
                firstClassRadio3 = new javax.swing.JRadioButton();
                firstClassRadio4 = new javax.swing.JRadioButton();
                firstClassRadio5 = new javax.swing.JRadioButton();
                firstClassRadio6 = new javax.swing.JRadioButton();
                firstClassRadio7 = new javax.swing.JRadioButton();
                firstClassRadio8 = new javax.swing.JRadioButton();
                firstClassRadio9 = new javax.swing.JRadioButton();
                firstClassRadio10 = new javax.swing.JRadioButton();
                firstClassRadio11 = new javax.swing.JRadioButton();
                firstClassRadio12 = new javax.swing.JRadioButton();
                premiumClassRadio1 = new javax.swing.JRadioButton();
                premiumClassRadio2 = new javax.swing.JRadioButton();
                premiumClassRadio3 = new javax.swing.JRadioButton();
                premiumClassRadio4 = new javax.swing.JRadioButton();
                premiumClassRadio5 = new javax.swing.JRadioButton();
                premiumClassRadio6 = new javax.swing.JRadioButton();
                premiumClassRadio7 = new javax.swing.JRadioButton();
                premiumClassRadio8 = new javax.swing.JRadioButton();
                premiumClassRadio9 = new javax.swing.JRadioButton();
                premiumClassRadio10 = new javax.swing.JRadioButton();
                premiumClassRadio11 = new javax.swing.JRadioButton();
                premiumClassRadio12 = new javax.swing.JRadioButton();
                premiumClassRadio13 = new javax.swing.JRadioButton();
                premiumClassRadio14 = new javax.swing.JRadioButton();
                premiumClassRadio15 = new javax.swing.JRadioButton();
                premiumClassRadio16 = new javax.swing.JRadioButton();
                premiumClassRadio17 = new javax.swing.JRadioButton();
                premiumClassRadio18 = new javax.swing.JRadioButton();
                premiumClassRadio19 = new javax.swing.JRadioButton();
                premiumClassRadio20 = new javax.swing.JRadioButton();
                premiumClassRadio21 = new javax.swing.JRadioButton();
                premiumClassRadio22 = new javax.swing.JRadioButton();
                premiumClassRadio23 = new javax.swing.JRadioButton();
                premiumClassRadio24 = new javax.swing.JRadioButton();
                premiumClassRadio25 = new javax.swing.JRadioButton();
                premiumClassRadio26 = new javax.swing.JRadioButton();
                premiumClassRadio27 = new javax.swing.JRadioButton();
                premiumClassRadio28 = new javax.swing.JRadioButton();
                premiumClassRadio29 = new javax.swing.JRadioButton();
                premiumClassRadio30 = new javax.swing.JRadioButton();
                mainCabinRadio1 = new javax.swing.JRadioButton();
                mainCabinRadio2 = new javax.swing.JRadioButton();
                mainCabinRadio3 = new javax.swing.JRadioButton();
                mainCabinRadio4 = new javax.swing.JRadioButton();
                mainCabinRadio5 = new javax.swing.JRadioButton();
                mainCabinRadio6 = new javax.swing.JRadioButton();
                mainCabinRadio7 = new javax.swing.JRadioButton();
                mainCabinRadio8 = new javax.swing.JRadioButton();
                mainCabinRadio9 = new javax.swing.JRadioButton();
                mainCabinRadio10 = new javax.swing.JRadioButton();
                mainCabinRadio11 = new javax.swing.JRadioButton();
                mainCabinRadio12 = new javax.swing.JRadioButton();
                mainCabinRadio13 = new javax.swing.JRadioButton();
                mainCabinRadio14 = new javax.swing.JRadioButton();
                mainCabinRadio15 = new javax.swing.JRadioButton();
                mainCabinRadio16 = new javax.swing.JRadioButton();
                mainCabinRadio17 = new javax.swing.JRadioButton();
                mainCabinRadio18 = new javax.swing.JRadioButton();
                mainCabinRadio19 = new javax.swing.JRadioButton();
                mainCabinRadio20 = new javax.swing.JRadioButton();
                mainCabinRadio21 = new javax.swing.JRadioButton();
                mainCabinRadio22 = new javax.swing.JRadioButton();
                mainCabinRadio23 = new javax.swing.JRadioButton();
                mainCabinRadio24 = new javax.swing.JRadioButton();
                mainCabinRadio25 = new javax.swing.JRadioButton();
                mainCabinRadio26 = new javax.swing.JRadioButton();
                mainCabinRadio27 = new javax.swing.JRadioButton();
                mainCabinRadio28 = new javax.swing.JRadioButton();
                mainCabinRadio29 = new javax.swing.JRadioButton();
                mainCabinRadio30 = new javax.swing.JRadioButton();
                mainCabinRadio31 = new javax.swing.JRadioButton();
                mainCabinRadio32 = new javax.swing.JRadioButton();
                mainCabinRadio33 = new javax.swing.JRadioButton();
                mainCabinRadio34 = new javax.swing.JRadioButton();
                mainCabinRadio35 = new javax.swing.JRadioButton();
                mainCabinRadio36 = new javax.swing.JRadioButton();
                mainCabinRadio37 = new javax.swing.JRadioButton();
                mainCabinRadio38 = new javax.swing.JRadioButton();
                mainCabinRadio39 = new javax.swing.JRadioButton();
                mainCabinRadio40 = new javax.swing.JRadioButton();
                mainCabinRadio41 = new javax.swing.JRadioButton();
                mainCabinRadio42 = new javax.swing.JRadioButton();
                mainCabinRadio43 = new javax.swing.JRadioButton();
                mainCabinRadio44 = new javax.swing.JRadioButton();
                mainCabinRadio45 = new javax.swing.JRadioButton();
                mainCabinRadio46 = new javax.swing.JRadioButton();
                mainCabinRadio47 = new javax.swing.JRadioButton();
                mainCabinRadio48 = new javax.swing.JRadioButton();
                mainCabinRadio49 = new javax.swing.JRadioButton();
                mainCabinRadio50 = new javax.swing.JRadioButton();
                mainCabinRadio51 = new javax.swing.JRadioButton();
                mainCabinRadio52 = new javax.swing.JRadioButton();
                mainCabinRadio53 = new javax.swing.JRadioButton();
                mainCabinRadio54 = new javax.swing.JRadioButton();
                mainCabinRadio55 = new javax.swing.JRadioButton();
                mainCabinRadio56 = new javax.swing.JRadioButton();
                mainCabinRadio57 = new javax.swing.JRadioButton();
                mainCabinRadio58 = new javax.swing.JRadioButton();
                mainCabinRadio59 = new javax.swing.JRadioButton();
                mainCabinRadio60 = new javax.swing.JRadioButton();
                mainCabinRadio61 = new javax.swing.JRadioButton();
                mainCabinRadio62 = new javax.swing.JRadioButton();
                mainCabinRadio63 = new javax.swing.JRadioButton();
                mainCabinRadio64 = new javax.swing.JRadioButton();
                mainCabinRadio65 = new javax.swing.JRadioButton();
                mainCabinRadio66 = new javax.swing.JRadioButton();
                mainCabinRadio67 = new javax.swing.JRadioButton();
                mainCabinRadio68 = new javax.swing.JRadioButton();
                mainCabinRadio69 = new javax.swing.JRadioButton();
                mainCabinRadio70 = new javax.swing.JRadioButton();
                mainCabinRadio71 = new javax.swing.JRadioButton();
                mainCabinRadio72 = new javax.swing.JRadioButton();
                mainCabinRadio73 = new javax.swing.JRadioButton();
                mainCabinRadio74 = new javax.swing.JRadioButton();
                mainCabinRadio75 = new javax.swing.JRadioButton();
                mainCabinRadio76 = new javax.swing.JRadioButton();
                mainCabinRadio77 = new javax.swing.JRadioButton();
                mainCabinRadio78 = new javax.swing.JRadioButton();
                mainCabinRadio79 = new javax.swing.JRadioButton();
                mainCabinRadio80 = new javax.swing.JRadioButton();
                mainCabinRadio81 = new javax.swing.JRadioButton();
                mainCabinRadio82 = new javax.swing.JRadioButton();
                mainCabinRadio83 = new javax.swing.JRadioButton();
                mainCabinRadio84 = new javax.swing.JRadioButton();
                mainCabinRadio85 = new javax.swing.JRadioButton();
                mainCabinRadio86 = new javax.swing.JRadioButton();
                mainCabinRadio87 = new javax.swing.JRadioButton();
                mainCabinRadio88 = new javax.swing.JRadioButton();
                mainCabinRadio89 = new javax.swing.JRadioButton();
                mainCabinRadio90 = new javax.swing.JRadioButton();
                mainCabinRadio91 = new javax.swing.JRadioButton();
                mainCabinRadio92 = new javax.swing.JRadioButton();
                mainCabinRadio93 = new javax.swing.JRadioButton();
                mainCabinRadio94 = new javax.swing.JRadioButton();
                mainCabinRadio95 = new javax.swing.JRadioButton();
                mainCabinRadio96 = new javax.swing.JRadioButton();
                mainCabinRadio97 = new javax.swing.JRadioButton();
                mainCabinRadio98 = new javax.swing.JRadioButton();
                mainCabinRadio99 = new javax.swing.JRadioButton();
                mainCabinRadio100 = new javax.swing.JRadioButton();
                mainCabinRadio101 = new javax.swing.JRadioButton();
                mainCabinRadio102 = new javax.swing.JRadioButton();
                mainCabinRadio103 = new javax.swing.JRadioButton();
                mainCabinRadio104 = new javax.swing.JRadioButton();
                mainCabinRadio105 = new javax.swing.JRadioButton();
                mainCabinRadio106 = new javax.swing.JRadioButton();
                mainCabinRadio107 = new javax.swing.JRadioButton();
                mainCabinRadio108 = new javax.swing.JRadioButton();
                mainCabinRadio109 = new javax.swing.JRadioButton();
                mainCabinRadio110 = new javax.swing.JRadioButton();
                mainCabinRadio111 = new javax.swing.JRadioButton();
                mainCabinRadio112 = new javax.swing.JRadioButton();
                mainCabinRadio113 = new javax.swing.JRadioButton();
                mainCabinRadio114 = new javax.swing.JRadioButton();
                mainCabinRadio115 = new javax.swing.JRadioButton();
                mainCabinRadio116 = new javax.swing.JRadioButton();
                mainCabinRadio117 = new javax.swing.JRadioButton();
                mainCabinPrice = new javax.swing.JLabel();
                premiumClassPrice = new javax.swing.JLabel();
                firstClassPrice = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Flight Tickets");
                setBounds(new java.awt.Rectangle(500, 400, 0, 0));
                setResizable(false);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setBackground(new java.awt.Color(225, 255, 255));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                buyTheTicketButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                buyTheTicketButton.setText("Buy The Ticket");
                buyTheTicketButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buyTheTicketButtonActionPerformed(evt);
                        }
                });
                jPanel1.add(buyTheTicketButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, -1));

                seatsButtonGroup.add(firstClassRadio1);
                jPanel1.add(firstClassRadio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

                seatsButtonGroup.add(firstClassRadio2);
                jPanel1.add(firstClassRadio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

                seatsButtonGroup.add(firstClassRadio3);
                jPanel1.add(firstClassRadio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

                seatsButtonGroup.add(firstClassRadio4);
                jPanel1.add(firstClassRadio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

                seatsButtonGroup.add(firstClassRadio5);
                jPanel1.add(firstClassRadio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

                seatsButtonGroup.add(firstClassRadio6);
                jPanel1.add(firstClassRadio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

                seatsButtonGroup.add(firstClassRadio7);
                jPanel1.add(firstClassRadio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

                seatsButtonGroup.add(firstClassRadio8);
                jPanel1.add(firstClassRadio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

                seatsButtonGroup.add(firstClassRadio9);
                jPanel1.add(firstClassRadio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

                seatsButtonGroup.add(firstClassRadio10);
                jPanel1.add(firstClassRadio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

                seatsButtonGroup.add(firstClassRadio11);
                jPanel1.add(firstClassRadio11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

                seatsButtonGroup.add(firstClassRadio12);
                jPanel1.add(firstClassRadio12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

                seatsButtonGroup.add(premiumClassRadio1);
                jPanel1.add(premiumClassRadio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

                seatsButtonGroup.add(premiumClassRadio2);
                jPanel1.add(premiumClassRadio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

                seatsButtonGroup.add(premiumClassRadio3);
                jPanel1.add(premiumClassRadio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

                seatsButtonGroup.add(premiumClassRadio4);
                jPanel1.add(premiumClassRadio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

                seatsButtonGroup.add(premiumClassRadio5);
                jPanel1.add(premiumClassRadio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

                seatsButtonGroup.add(premiumClassRadio6);
                jPanel1.add(premiumClassRadio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

                seatsButtonGroup.add(premiumClassRadio7);
                jPanel1.add(premiumClassRadio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

                seatsButtonGroup.add(premiumClassRadio8);
                jPanel1.add(premiumClassRadio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

                seatsButtonGroup.add(premiumClassRadio9);
                jPanel1.add(premiumClassRadio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

                seatsButtonGroup.add(premiumClassRadio10);
                jPanel1.add(premiumClassRadio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

                seatsButtonGroup.add(premiumClassRadio11);
                jPanel1.add(premiumClassRadio11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

                seatsButtonGroup.add(premiumClassRadio12);
                jPanel1.add(premiumClassRadio12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

                seatsButtonGroup.add(premiumClassRadio13);
                jPanel1.add(premiumClassRadio13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

                seatsButtonGroup.add(premiumClassRadio14);
                jPanel1.add(premiumClassRadio14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

                seatsButtonGroup.add(premiumClassRadio15);
                jPanel1.add(premiumClassRadio15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

                seatsButtonGroup.add(premiumClassRadio16);
                jPanel1.add(premiumClassRadio16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

                seatsButtonGroup.add(premiumClassRadio17);
                jPanel1.add(premiumClassRadio17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

                seatsButtonGroup.add(premiumClassRadio18);
                jPanel1.add(premiumClassRadio18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

                seatsButtonGroup.add(premiumClassRadio19);
                jPanel1.add(premiumClassRadio19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

                seatsButtonGroup.add(premiumClassRadio20);
                jPanel1.add(premiumClassRadio20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

                seatsButtonGroup.add(premiumClassRadio21);
                jPanel1.add(premiumClassRadio21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

                seatsButtonGroup.add(premiumClassRadio22);
                jPanel1.add(premiumClassRadio22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

                seatsButtonGroup.add(premiumClassRadio23);
                jPanel1.add(premiumClassRadio23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

                seatsButtonGroup.add(premiumClassRadio24);
                jPanel1.add(premiumClassRadio24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

                seatsButtonGroup.add(premiumClassRadio25);
                jPanel1.add(premiumClassRadio25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

                seatsButtonGroup.add(premiumClassRadio26);
                jPanel1.add(premiumClassRadio26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

                seatsButtonGroup.add(premiumClassRadio27);
                jPanel1.add(premiumClassRadio27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

                seatsButtonGroup.add(premiumClassRadio28);
                jPanel1.add(premiumClassRadio28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

                seatsButtonGroup.add(premiumClassRadio29);
                jPanel1.add(premiumClassRadio29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

                seatsButtonGroup.add(premiumClassRadio30);
                jPanel1.add(premiumClassRadio30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio1);
                jPanel1.add(mainCabinRadio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio2);
                jPanel1.add(mainCabinRadio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio3);
                jPanel1.add(mainCabinRadio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio4);
                jPanel1.add(mainCabinRadio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio5);
                jPanel1.add(mainCabinRadio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio6);
                jPanel1.add(mainCabinRadio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio7);
                jPanel1.add(mainCabinRadio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio8);
                jPanel1.add(mainCabinRadio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio9);
                jPanel1.add(mainCabinRadio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio10);
                jPanel1.add(mainCabinRadio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio11);
                jPanel1.add(mainCabinRadio11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio12);
                jPanel1.add(mainCabinRadio12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio13);
                jPanel1.add(mainCabinRadio13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio14);
                jPanel1.add(mainCabinRadio14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio15);
                jPanel1.add(mainCabinRadio15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio16);
                jPanel1.add(mainCabinRadio16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio17);
                jPanel1.add(mainCabinRadio17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio18);
                jPanel1.add(mainCabinRadio18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio19);
                jPanel1.add(mainCabinRadio19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio20);
                jPanel1.add(mainCabinRadio20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio21);
                jPanel1.add(mainCabinRadio21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio22);
                jPanel1.add(mainCabinRadio22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio23);
                jPanel1.add(mainCabinRadio23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio24);
                jPanel1.add(mainCabinRadio24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio25);
                jPanel1.add(mainCabinRadio25, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio26);
                jPanel1.add(mainCabinRadio26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio27);
                jPanel1.add(mainCabinRadio27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio28);
                jPanel1.add(mainCabinRadio28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio29);
                jPanel1.add(mainCabinRadio29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio30);
                jPanel1.add(mainCabinRadio30, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio31);
                jPanel1.add(mainCabinRadio31, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio32);
                jPanel1.add(mainCabinRadio32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio33);
                jPanel1.add(mainCabinRadio33, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio34);
                jPanel1.add(mainCabinRadio34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio35);
                jPanel1.add(mainCabinRadio35, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio36);
                jPanel1.add(mainCabinRadio36, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio37);
                jPanel1.add(mainCabinRadio37, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio38);
                jPanel1.add(mainCabinRadio38, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio39);
                jPanel1.add(mainCabinRadio39, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio40);
                jPanel1.add(mainCabinRadio40, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio41);
                jPanel1.add(mainCabinRadio41, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio42);
                jPanel1.add(mainCabinRadio42, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio43);
                jPanel1.add(mainCabinRadio43, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio44);
                jPanel1.add(mainCabinRadio44, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio45);
                jPanel1.add(mainCabinRadio45, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio46);
                jPanel1.add(mainCabinRadio46, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio47);
                jPanel1.add(mainCabinRadio47, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio48);
                jPanel1.add(mainCabinRadio48, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio49);
                jPanel1.add(mainCabinRadio49, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio50);
                jPanel1.add(mainCabinRadio50, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio51);
                jPanel1.add(mainCabinRadio51, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio52);
                jPanel1.add(mainCabinRadio52, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio53);
                jPanel1.add(mainCabinRadio53, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio54);
                jPanel1.add(mainCabinRadio54, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio55);
                jPanel1.add(mainCabinRadio55, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio56);
                jPanel1.add(mainCabinRadio56, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio57);
                jPanel1.add(mainCabinRadio57, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio58);
                jPanel1.add(mainCabinRadio58, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio59);
                jPanel1.add(mainCabinRadio59, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio60);
                jPanel1.add(mainCabinRadio60, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio61);
                jPanel1.add(mainCabinRadio61, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio62);
                jPanel1.add(mainCabinRadio62, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio63);
                jPanel1.add(mainCabinRadio63, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio64);
                jPanel1.add(mainCabinRadio64, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio65);
                jPanel1.add(mainCabinRadio65, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio66);
                jPanel1.add(mainCabinRadio66, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio67);
                jPanel1.add(mainCabinRadio67, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio68);
                jPanel1.add(mainCabinRadio68, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio69);
                jPanel1.add(mainCabinRadio69, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio70);
                jPanel1.add(mainCabinRadio70, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio71);
                jPanel1.add(mainCabinRadio71, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio72);
                jPanel1.add(mainCabinRadio72, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio73);
                jPanel1.add(mainCabinRadio73, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio74);
                jPanel1.add(mainCabinRadio74, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio75);
                jPanel1.add(mainCabinRadio75, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio76);
                jPanel1.add(mainCabinRadio76, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio77);
                jPanel1.add(mainCabinRadio77, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio78);
                jPanel1.add(mainCabinRadio78, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio79);
                jPanel1.add(mainCabinRadio79, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio80);
                jPanel1.add(mainCabinRadio80, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio81);
                jPanel1.add(mainCabinRadio81, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio82);
                jPanel1.add(mainCabinRadio82, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio83);
                jPanel1.add(mainCabinRadio83, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio84);
                jPanel1.add(mainCabinRadio84, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio85);
                jPanel1.add(mainCabinRadio85, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio86);
                jPanel1.add(mainCabinRadio86, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio87);
                jPanel1.add(mainCabinRadio87, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio88);
                jPanel1.add(mainCabinRadio88, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio89);
                jPanel1.add(mainCabinRadio89, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio90);
                jPanel1.add(mainCabinRadio90, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio91);
                jPanel1.add(mainCabinRadio91, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio92);
                jPanel1.add(mainCabinRadio92, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio93);
                jPanel1.add(mainCabinRadio93, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio94);
                jPanel1.add(mainCabinRadio94, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio95);
                jPanel1.add(mainCabinRadio95, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio96);
                jPanel1.add(mainCabinRadio96, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio97);
                jPanel1.add(mainCabinRadio97, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio98);
                jPanel1.add(mainCabinRadio98, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio99);
                jPanel1.add(mainCabinRadio99, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio100);
                jPanel1.add(mainCabinRadio100, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio101);
                jPanel1.add(mainCabinRadio101, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio102);
                jPanel1.add(mainCabinRadio102, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio103);
                jPanel1.add(mainCabinRadio103, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio104);
                jPanel1.add(mainCabinRadio104, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio105);
                jPanel1.add(mainCabinRadio105, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio106);
                jPanel1.add(mainCabinRadio106, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio107);
                jPanel1.add(mainCabinRadio107, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio108);
                jPanel1.add(mainCabinRadio108, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio109);
                jPanel1.add(mainCabinRadio109, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, -1, -1));

                seatsButtonGroup.add(mainCabinRadio110);
                jPanel1.add(mainCabinRadio110, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, -1));

                seatsButtonGroup.add(mainCabinRadio111);
                jPanel1.add(mainCabinRadio111, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, -1));

                seatsButtonGroup.add(mainCabinRadio112);
                jPanel1.add(mainCabinRadio112, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio113);
                jPanel1.add(mainCabinRadio113, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio114);
                jPanel1.add(mainCabinRadio114, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, -1));

                seatsButtonGroup.add(mainCabinRadio115);
                jPanel1.add(mainCabinRadio115, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, -1, -1));

                seatsButtonGroup.add(mainCabinRadio116);
                jPanel1.add(mainCabinRadio116, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, -1, -1));

                seatsButtonGroup.add(mainCabinRadio117);
                jPanel1.add(mainCabinRadio117, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, -1, -1));

                mainCabinPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                mainCabinPrice.setText("100$");
                jPanel1.add(mainCabinPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

                premiumClassPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                premiumClassPrice.setText("200$");
                jPanel1.add(premiumClassPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

                firstClassPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                firstClassPrice.setText("300$");
                jPanel1.add(firstClassPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flighttickets/seats.png"))); // NOI18N
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 940, 460));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void buyTheTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTheTicketButtonActionPerformed
		boolean flag = true;

		for (Enumeration<AbstractButton> buttons = seatsButtonGroup.getElements(); buttons.hasMoreElements();) {
			AbstractButton button = buttons.nextElement();

			if(button.isSelected()) {
				flag = false;
			}
		}

		if(flag) { // shows an error if the seat is not selected
			JOptionPane.showMessageDialog(this, "Please select a seat.");
		}

		else {
			this.seatNumber = Integer.valueOf(this.seatsButtonGroup.getSelection().getActionCommand());

			PaymentPage paymentPage = new PaymentPage(this.planeId, this.customerId, seatNumber, this.buyTicket, this);
			paymentPage.setVisible(true); // opens a paymentPage
		}
        }//GEN-LAST:event_buyTheTicketButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ChooseSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ChooseSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ChooseSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ChooseSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		 //</editor-fold>

		/* Create and display the form */
		/*java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChooseSeat().setVisible(true);
			}
		});*/
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton buyTheTicketButton;
        private javax.swing.JLabel firstClassPrice;
        private javax.swing.JRadioButton firstClassRadio1;
        private javax.swing.JRadioButton firstClassRadio10;
        private javax.swing.JRadioButton firstClassRadio11;
        private javax.swing.JRadioButton firstClassRadio12;
        private javax.swing.JRadioButton firstClassRadio2;
        private javax.swing.JRadioButton firstClassRadio3;
        private javax.swing.JRadioButton firstClassRadio4;
        private javax.swing.JRadioButton firstClassRadio5;
        private javax.swing.JRadioButton firstClassRadio6;
        private javax.swing.JRadioButton firstClassRadio7;
        private javax.swing.JRadioButton firstClassRadio8;
        private javax.swing.JRadioButton firstClassRadio9;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel mainCabinPrice;
        private javax.swing.JRadioButton mainCabinRadio1;
        private javax.swing.JRadioButton mainCabinRadio10;
        private javax.swing.JRadioButton mainCabinRadio100;
        private javax.swing.JRadioButton mainCabinRadio101;
        private javax.swing.JRadioButton mainCabinRadio102;
        private javax.swing.JRadioButton mainCabinRadio103;
        private javax.swing.JRadioButton mainCabinRadio104;
        private javax.swing.JRadioButton mainCabinRadio105;
        private javax.swing.JRadioButton mainCabinRadio106;
        private javax.swing.JRadioButton mainCabinRadio107;
        private javax.swing.JRadioButton mainCabinRadio108;
        private javax.swing.JRadioButton mainCabinRadio109;
        private javax.swing.JRadioButton mainCabinRadio11;
        private javax.swing.JRadioButton mainCabinRadio110;
        private javax.swing.JRadioButton mainCabinRadio111;
        private javax.swing.JRadioButton mainCabinRadio112;
        private javax.swing.JRadioButton mainCabinRadio113;
        private javax.swing.JRadioButton mainCabinRadio114;
        private javax.swing.JRadioButton mainCabinRadio115;
        private javax.swing.JRadioButton mainCabinRadio116;
        private javax.swing.JRadioButton mainCabinRadio117;
        private javax.swing.JRadioButton mainCabinRadio12;
        private javax.swing.JRadioButton mainCabinRadio13;
        private javax.swing.JRadioButton mainCabinRadio14;
        private javax.swing.JRadioButton mainCabinRadio15;
        private javax.swing.JRadioButton mainCabinRadio16;
        private javax.swing.JRadioButton mainCabinRadio17;
        private javax.swing.JRadioButton mainCabinRadio18;
        private javax.swing.JRadioButton mainCabinRadio19;
        private javax.swing.JRadioButton mainCabinRadio2;
        private javax.swing.JRadioButton mainCabinRadio20;
        private javax.swing.JRadioButton mainCabinRadio21;
        private javax.swing.JRadioButton mainCabinRadio22;
        private javax.swing.JRadioButton mainCabinRadio23;
        private javax.swing.JRadioButton mainCabinRadio24;
        private javax.swing.JRadioButton mainCabinRadio25;
        private javax.swing.JRadioButton mainCabinRadio26;
        private javax.swing.JRadioButton mainCabinRadio27;
        private javax.swing.JRadioButton mainCabinRadio28;
        private javax.swing.JRadioButton mainCabinRadio29;
        private javax.swing.JRadioButton mainCabinRadio3;
        private javax.swing.JRadioButton mainCabinRadio30;
        private javax.swing.JRadioButton mainCabinRadio31;
        private javax.swing.JRadioButton mainCabinRadio32;
        private javax.swing.JRadioButton mainCabinRadio33;
        private javax.swing.JRadioButton mainCabinRadio34;
        private javax.swing.JRadioButton mainCabinRadio35;
        private javax.swing.JRadioButton mainCabinRadio36;
        private javax.swing.JRadioButton mainCabinRadio37;
        private javax.swing.JRadioButton mainCabinRadio38;
        private javax.swing.JRadioButton mainCabinRadio39;
        private javax.swing.JRadioButton mainCabinRadio4;
        private javax.swing.JRadioButton mainCabinRadio40;
        private javax.swing.JRadioButton mainCabinRadio41;
        private javax.swing.JRadioButton mainCabinRadio42;
        private javax.swing.JRadioButton mainCabinRadio43;
        private javax.swing.JRadioButton mainCabinRadio44;
        private javax.swing.JRadioButton mainCabinRadio45;
        private javax.swing.JRadioButton mainCabinRadio46;
        private javax.swing.JRadioButton mainCabinRadio47;
        private javax.swing.JRadioButton mainCabinRadio48;
        private javax.swing.JRadioButton mainCabinRadio49;
        private javax.swing.JRadioButton mainCabinRadio5;
        private javax.swing.JRadioButton mainCabinRadio50;
        private javax.swing.JRadioButton mainCabinRadio51;
        private javax.swing.JRadioButton mainCabinRadio52;
        private javax.swing.JRadioButton mainCabinRadio53;
        private javax.swing.JRadioButton mainCabinRadio54;
        private javax.swing.JRadioButton mainCabinRadio55;
        private javax.swing.JRadioButton mainCabinRadio56;
        private javax.swing.JRadioButton mainCabinRadio57;
        private javax.swing.JRadioButton mainCabinRadio58;
        private javax.swing.JRadioButton mainCabinRadio59;
        private javax.swing.JRadioButton mainCabinRadio6;
        private javax.swing.JRadioButton mainCabinRadio60;
        private javax.swing.JRadioButton mainCabinRadio61;
        private javax.swing.JRadioButton mainCabinRadio62;
        private javax.swing.JRadioButton mainCabinRadio63;
        private javax.swing.JRadioButton mainCabinRadio64;
        private javax.swing.JRadioButton mainCabinRadio65;
        private javax.swing.JRadioButton mainCabinRadio66;
        private javax.swing.JRadioButton mainCabinRadio67;
        private javax.swing.JRadioButton mainCabinRadio68;
        private javax.swing.JRadioButton mainCabinRadio69;
        private javax.swing.JRadioButton mainCabinRadio7;
        private javax.swing.JRadioButton mainCabinRadio70;
        private javax.swing.JRadioButton mainCabinRadio71;
        private javax.swing.JRadioButton mainCabinRadio72;
        private javax.swing.JRadioButton mainCabinRadio73;
        private javax.swing.JRadioButton mainCabinRadio74;
        private javax.swing.JRadioButton mainCabinRadio75;
        private javax.swing.JRadioButton mainCabinRadio76;
        private javax.swing.JRadioButton mainCabinRadio77;
        private javax.swing.JRadioButton mainCabinRadio78;
        private javax.swing.JRadioButton mainCabinRadio79;
        private javax.swing.JRadioButton mainCabinRadio8;
        private javax.swing.JRadioButton mainCabinRadio80;
        private javax.swing.JRadioButton mainCabinRadio81;
        private javax.swing.JRadioButton mainCabinRadio82;
        private javax.swing.JRadioButton mainCabinRadio83;
        private javax.swing.JRadioButton mainCabinRadio84;
        private javax.swing.JRadioButton mainCabinRadio85;
        private javax.swing.JRadioButton mainCabinRadio86;
        private javax.swing.JRadioButton mainCabinRadio87;
        private javax.swing.JRadioButton mainCabinRadio88;
        private javax.swing.JRadioButton mainCabinRadio89;
        private javax.swing.JRadioButton mainCabinRadio9;
        private javax.swing.JRadioButton mainCabinRadio90;
        private javax.swing.JRadioButton mainCabinRadio91;
        private javax.swing.JRadioButton mainCabinRadio92;
        private javax.swing.JRadioButton mainCabinRadio93;
        private javax.swing.JRadioButton mainCabinRadio94;
        private javax.swing.JRadioButton mainCabinRadio95;
        private javax.swing.JRadioButton mainCabinRadio96;
        private javax.swing.JRadioButton mainCabinRadio97;
        private javax.swing.JRadioButton mainCabinRadio98;
        private javax.swing.JRadioButton mainCabinRadio99;
        private javax.swing.JLabel premiumClassPrice;
        private javax.swing.JRadioButton premiumClassRadio1;
        private javax.swing.JRadioButton premiumClassRadio10;
        private javax.swing.JRadioButton premiumClassRadio11;
        private javax.swing.JRadioButton premiumClassRadio12;
        private javax.swing.JRadioButton premiumClassRadio13;
        private javax.swing.JRadioButton premiumClassRadio14;
        private javax.swing.JRadioButton premiumClassRadio15;
        private javax.swing.JRadioButton premiumClassRadio16;
        private javax.swing.JRadioButton premiumClassRadio17;
        private javax.swing.JRadioButton premiumClassRadio18;
        private javax.swing.JRadioButton premiumClassRadio19;
        private javax.swing.JRadioButton premiumClassRadio2;
        private javax.swing.JRadioButton premiumClassRadio20;
        private javax.swing.JRadioButton premiumClassRadio21;
        private javax.swing.JRadioButton premiumClassRadio22;
        private javax.swing.JRadioButton premiumClassRadio23;
        private javax.swing.JRadioButton premiumClassRadio24;
        private javax.swing.JRadioButton premiumClassRadio25;
        private javax.swing.JRadioButton premiumClassRadio26;
        private javax.swing.JRadioButton premiumClassRadio27;
        private javax.swing.JRadioButton premiumClassRadio28;
        private javax.swing.JRadioButton premiumClassRadio29;
        private javax.swing.JRadioButton premiumClassRadio3;
        private javax.swing.JRadioButton premiumClassRadio30;
        private javax.swing.JRadioButton premiumClassRadio4;
        private javax.swing.JRadioButton premiumClassRadio5;
        private javax.swing.JRadioButton premiumClassRadio6;
        private javax.swing.JRadioButton premiumClassRadio7;
        private javax.swing.JRadioButton premiumClassRadio8;
        private javax.swing.JRadioButton premiumClassRadio9;
        private javax.swing.ButtonGroup seatsButtonGroup;
        // End of variables declaration//GEN-END:variables

}
